### ISSUE TITLE
Content jumps in NavigationBar and StatusBar is visible

### ISSUE THREAD

**Issue by grundid** [Ramotion/expanding-collection#14]
When I have a  StatusBar and NavigationBar visible the card jumps on user interactions. Also when I return from the TableViewController the vertical offset is not quite correct.

Is it possible to use this component with StatusBar and NavigationBar visible?

**Comment by 0ber** [comment]
I didn't implement it. I hope fix it soon

**Comment by 0ber** [comment]
example with navigation bar in  `with-navigation-bar` branch
