### ISSUE TITLE
Problem with carthage!!

### ISSUE THREAD

**Issue by Dershowitz011** [Ramotion/expanding-collection#16]
When I use this framework from carthage, I am unable to inherit from `BasePageCollectionCell`. But when I copy the `source` file directly to my project, everything work fine. When I inherit from `BasePageCollectionCell` using carthage, I'm just unable to assign the class to the cell.xib. Please fix. Thanks.

**Comment by 0ber** [comment]
works fine look my quick example https://github.com/ober01/ExpandingCollection-Example

**Comment by Dershowitz011** [comment]
I'll try it and let you know @ober01 ! Thank you!

**Comment by Dershowitz011** [comment]
@ober01 I'm just not able to do with Carthage! What Could I be doing wrong? :(
