### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by hdoria** [Ramotion/expanding-collection#24]
Any plans for Swift 3 support?

**Comment by ghost** [comment]
I would love to use this project inside my App so Swift 3 support would be great!

**Comment by arch1t3ct** [comment]
You can try my fork: https://github.com/arch1t3ct/expanding-collection/tree/swift3 

It should work, but no promises. There were places where I was quite not familiar with, so I used my best guess to fix it. Not sure if it's pull request worthy.
