### ISSUE TITLE
Problem with Sliding CollectionView

### ISSUE THREAD

**Issue by ganjmeng** [Ramotion/expanding-collection#25]
Hi!  Ramotion

I found a bug,  when I set ItemWidth > 270 ,some problem will happe， I can't fix it, I  need your help! Thanks!!!
![untitled23](https://cloud.githubusercontent.com/assets/12026835/17287234/ffc61dd6-5800-11e6-9fea-24340f72903e.gif)

My English is so bad, I hope you can understand what I mean. Thank you!

**Comment by ganjmeng** [comment]
when I set ItemWidth > 270 , if I want to scroll item from index 1 to index 0, it will be not back

**Comment by ganjmeng** [comment]
![untitled232](https://cloud.githubusercontent.com/assets/12026835/17287627/5f1b3a4e-5803-11e6-9883-2d29b7b19db1.gif)

**Comment by Laptopmini** [comment]
+1

**Comment by 0ber** [comment]
Can't reproduce 
![280](https://user-images.githubusercontent.com/5435782/35375638-cfcf52e2-01b8-11e8-9a70-03e5f978be0f.gif)
