### ISSUE TITLE
Cannot override with a stored property 'frontContainerView'

### ISSUE THREAD

**Issue by jayvenn** [Ramotion/expanding-collection#26]
I am trying to follow the instruction on creating a custom cell. Every time I assign the cell this particular name I get the error in the title. I am probably missing out on something. Help appreciated 👍

**Comment by git-hwa** [comment]
@nhantrivinh How did you fix this?

**Comment by lubos08** [comment]
After connecting them, just remove it solved problem for me.

**Comment by git-hwa** [comment]
I have linked it to parent collectionview cell.
But it occurs another problem.

```
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICollectionViewCell 0x7fce4641c3f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key backConstraintY.'
```

What did I wrong?

**Comment by rafaelcorreiapoli** [comment]
I'm also having this problem

**Comment by kanumuri9593** [comment]
If you followed the instructions you should have inherited your collectionView cell from BasePageCollectionCell
now command click BasePageCollectionCell and you will find all the outlets already created just connect those four IBOutlets to BasePageCollectionCell and rest to your own Cell


<img width="736" alt="screen shot 2017-04-08 at 9 48 42 am" src="https://cloud.githubusercontent.com/assets/16531000/24829496/e4407d68-1c40-11e7-9a93-d9dcff36e822.png">

**Comment by ElliotCunningham** [comment]
Hello everybody,

The problem is that you name your variables exactly with the same name as the parent class (frontConstraintY, backConstraintY is already declared in BasePageCollectionCell files) if you just change your variable names, you have no warning and no error
