### ISSUE TITLE
Need help understands View Archiving

### ISSUE THREAD

**Issue by ghost** [Ramotion/expanding-collection#31]
Hey there, 

Thank you very much for the great work and your contribution. 
I am having a hard time understanding the logic behind `archive` and `unarchive` in [TransitionDriver](https://github.com/Ramotion/expanding-collection/blob/master/Source/TransitionDriver/TransitionDriver.swift#L78). It seems the we are unarchiving right after archiving. Is there any specific reason for this.

**Comment by av0c0der** [comment]
@mosn this trick allow you to *copy* view object. If you add any view to some other view, it leaves superview and becomes to new one. You can't have one view object in two hierarchies and therefore you must have a *copy*.
