### ISSUE TITLE
How Can I Have The Second Container Show First

### ISSUE THREAD

**Issue by JayBone16** [Ramotion/expanding-collection#38]
How can I have the first index show instead of the zero index?

How It Shows Up When It Runs:
![screen shot 2016-10-10 at 2 37 31 pm](https://cloud.githubusercontent.com/assets/22697323/19252018/53985168-8ef7-11e6-8b8b-c99a7ed794a7.png)

How I want it to start up like:
![screen shot 2016-10-10 at 2 37 35 pm](https://cloud.githubusercontent.com/assets/22697323/19252039/7006bcc2-8ef7-11e6-8250-c62f600f8cce.png)

**Comment by git-hwa** [comment]
@JayBone16 Maybe you can manually select the item at the first launch.

```
self.collectionView?.selectItem(at: IndexPath(row: 1, section: 0), animated: true, scrollPosition: UICollectionViewScrollPosition.left)
```

**Comment by 0ber** [comment]
```
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)

    view.layoutIfNeeded()
    collectionView?.selectItem(at: IndexPath(row: <CURRENT_INDEX>, section: 0), animated: true, scrollPosition: .centeredHorizontally)
  }
```

**Comment by JayBone16** [comment]
@ober01 Thanks it worked!
