### ISSUE TITLE
ConfigurationHelper.swift Init func should be public

### ISSUE THREAD

**Issue by vaiStardom** [Ramotion/expanding-collection#41]
I could not access the func Init<Type>(...) as it is declared in the swift 3 version "internal func Init<Type>(_ ...". Had to change it to "public func Init<Type>(...)" so it could be reached by my project.

**Comment by 0ber** [comment]
this code just for easier configuration: http://nshipster.com/new-years-2016/ Easier Configuration

**Comment by younatics** [comment]
Needs to be public. I can't understand what you said :(
