### ISSUE TITLE
Is there any option to show card open in advanced without click on cell

### ISSUE THREAD

**Issue by sumeet85** [Ramotion/expanding-collection#54]
Hi

I m trying to open card cell without clicked the collection cell , I tried to set the value of isOpen true there is strange whiteout screen show first time 
Is there any option to show card open in advanced without click on cell

**Comment by av0c0der** [comment]
@sumeet85 instead of changing `isOpened` value directly, call `cellIsOpen` method with desired value.

```swift
cell.cellIsOpen(true)
```

**Comment by sumeet85** [comment]
Thanks for help
