### ISSUE TITLE
Error at numberOfItemsInSection

### ISSUE THREAD

**Issue by theesummer** [Ramotion/expanding-collection#61]
Hi There,

Thanks for this module. It was very useful.

In my current application, I created a customView class which will be called from the viewController. I have my delegate and data source methods set in the customView class. When I try to run the application, though I have assigned numberOfItemInSection, the app crashes at this point of line which is being added as an Image along with this issue. Please kindly acknowledge at the earliest

Thank you.
![screen shot 2017-06-15 at 11 02 46 am](https://user-images.githubusercontent.com/16913800/27166771-b8274450-51ba-11e7-8d95-4b1480324c2f.png)

**Comment by 0ber** [comment]
read https://github.com/Ramotion/expanding-collection#create-collectionviewcontroller
