### ISSUE TITLE
Demo Project: Title Label disappearing effect

### ISSUE THREAD

**Issue by thorng** [Ramotion/expanding-collection#64]
![sep-15-2017 17-50-34](https://user-images.githubusercontent.com/11326375/30507804-6c15ae72-9a3e-11e7-8558-61df5f9aa47b.gif)
How do I achieve the effect of the title label fading out like in your demo project? I've been searching in the code for days but can't find anything that specifically called that animation.

**Comment by 0ber** [comment]
read readme: 

> If set tag = 101 for any FrontView.subviews this view will be hidden during the transition animation

https://github.com/Ramotion/expanding-collection#if-set-tag--101-for-any-frontviewsubviews-this-view-will-be-hidden-during-the-transition-animation
