### ISSUE TITLE
Question that is not really related to the product, but why using extensions?

### ISSUE THREAD

**Issue by biogerm** [Ramotion/expanding-collection#65]
Hi Developers in Ramotion,

I was reading the example code included, and noticed that you are using extensions a lot. For example in DemoTableViewController, every methods are written as extensions. 

Is there any reason/benefit why you are writing it this way?

BR
AnChin

**Comment by RayanSaeed** [comment]
I wanna know as well..

**Comment by Laptopmini** [comment]
Swift 1 did not have pragma marks, which made extensions become the standard for code organization at the time.

The guidelines do not enforce this anymore, but it's still widely used.
https://swift.org/documentation/api-design-guidelines/

**Comment by 0ber** [comment]
it's just coding style, read this article https://www.natashatherobot.com/using-swift-extensions/

... and it's more readable 
![image](https://user-images.githubusercontent.com/5435782/33837344-13e67aee-de9d-11e7-9264-34ee002184a9.png)
