### ISSUE TITLE
Strange card deletion animation

### ISSUE THREAD

**Issue by achirkof** [Ramotion/expanding-collection#66]
Hi!
Thanks for this amazing extension!

My question is how I can override card deletion animation which behaviour is strange.

![remove_animation](https://user-images.githubusercontent.com/1292136/32078878-374fdb66-bab1-11e7-90d9-782ea454173a.gif)

As you can see on GIF when I tap green button it executes `collectionView.deleteItems(at: indexPath)` and animation is very strange.
First card climb to very top and then go down and disappearing.

I would like to card starting go down to the bottom from current position without rising up. How I can override `CollectionViewFlowLayout` attributes?

**Comment by achirkof** [comment]
I made an extension to override deletion animation. But it didn't solve problem when card jumps top before deletion.

```
extension PageCollectionLayout {
    
    override func prepare(forCollectionViewUpdates updateItems: [UICollectionViewUpdateItem]) {
        super.prepare(forCollectionViewUpdates: updateItems)
        removingIndexPaths.removeAll()
        
        for update in updateItems {
            if let indexPath = update.indexPathBeforeUpdate, update.updateAction == .delete {
                removingIndexPaths.append(indexPath)
            }
        }
    }
    
    override func finalizeCollectionViewUpdates() {
        super.finalizeCollectionViewUpdates()
        removingIndexPaths.removeAll()
    }
    
    override func finalLayoutAttributesForDisappearingItem(at itemIndexPath: IndexPath) -> UICollectionViewLayoutAttributes? {
        let attributes = super.finalLayoutAttributesForDisappearingItem(at: itemIndexPath)
        
        if removingIndexPaths.contains(itemIndexPath) {
            attributes?.transform = CGAffineTransform(scaleX: 0.1, y: 0.1)
        }
        print(attributes)
        return attributes
    }
}
```

@aleksei1000000 could you please help me to understand why it happening? 
Thanks

**Comment by StewartLynch** [comment]
With XCode 9.2 and 9.3, I get this Swift Compiler error on two lines in the BasePageCollectionCell.swift file  Lines 179 and 189
```
Expression type '[(NSLayoutAttribute, Double)]' is ambiguous without more context
I
```

**Comment by achirkof** [comment]
@ober01 great! Thank you very much! 🤝
