### ISSUE TITLE
Is it possible to have only the collection view with front view, but no back view?

### ISSUE THREAD

**Issue by junweimah** [Ramotion/expanding-collection#70]
Hi, 

I wanted to implement this library in my project, but however I don't need to have user to tap in to view details, just to scroll on the cards collection.

I have set up the basics xib, cell and delegate methods, but when I run it, i am getting at `line 154 of BasePageCollectionCell.swift: `

`backContainerView.layer.masksToBounds = true`

It is fatal error because it is nil, and it is nil because I don't need a back view. 

Is it possible to just set it up to have only the collection but no the back view?

Thanks

**Comment by 0ber** [comment]
In demo project I set isHidden to true for backView 
![set hidden](https://user-images.githubusercontent.com/5435782/35667773-f16bedf2-073f-11e8-913c-12af6e036cd4.png)

result: 
![result](https://user-images.githubusercontent.com/5435782/35667819-0a7131c2-0740-11e8-8e06-87bee6b6c182.gif)

**Comment by junweimah** [comment]
Thanks!
