### ISSUE TITLE
Skipping middle step

### ISSUE THREAD

**Issue by antonijap** [Ramotion/expanding-collection#76]
In your demo, there is some kind of a small reveal with information on first swipe up. I wonder if there is a way to skip this and just use fullscreen end view on swipe up or a tap?

**Comment by ARGAMX** [comment]
interested too

**Comment by 0ber** [comment]
https://github.com/Ramotion/expanding-collection/blob/master/Source/ExpandingViewController/ExpandingViewController.swift#L53-L57
