### ISSUE TITLE
Add target/gesture to AnimatingBarButton

### ISSUE THREAD

**Issue by fbernack** [Ramotion/expanding-collection#79]
Hello there,

i'm currently not able to add a target to the AnimatingBarButton appearing on the ExpandingViewController. I just want to execute a segue to another view controller on tap. I think because it's a custom view, i need to handle user interactions by myself, but i don't know how. 

Can anybody help?

Thank you very much.

Francis

**Comment by 0ber** [comment]
look for example https://github.com/Ramotion/expanding-collection/blob/master/DemoExpandingCollection/DemoExpandingCollection/ViewControllers/DemoTableViewController/DemoTableViewController.swift

and follow this steps https://github.com/Ramotion/expanding-collection#transition-animation

**Comment by fbernack** [comment]
Hi ober01, 
thanks for the quick reply, but i'm not sure if we're on the same page or i just don't get it.
I have problem with the UIBarButtonItem (`rightButton`) on the ExpandingViewController, not the ExpandingTableViewController. In the demo there is the crosshair icon. Is it possible to add a target to an independent action?

Francis

**Comment by 0ber** [comment]
The problem is `rightButton` inherited from `AnimationBarButton`. `AnimationBarButton` class is not a part of the library, it is just for a quick demo project. If right button inherited from UIBarButtonItem, action would be work
