### ISSUE TITLE
ReloadData does not call cellForRowAtIndexPath?

### ISSUE THREAD

**Issue by iphonerose** [Ramotion/expanding-collection#88]
This works just fine when I have an array I pass in and it displays cells correctly. But i have a flow where the tableviews data source needs to be reloaded after making a REST call. 

I am printing out number of row in section and seeing the correct numbers after I call dispatchQueue.main.async { self.tableView.reloadData();} but I never get into the cellForRowAtIndexPath method after calling reloadData??

**Comment by DanzerKnight05** [comment]
Heyy
